### ISSUE TITLE
ThermostatBeca New version DLX Control solutions

### ISSUE THREAD

**Issue by alessandrosalafia** [klausahrenberg/WThermostatBeca#149] opened 2020-10-30 13:43 UTC
Hi . I recently ordered new home thermostats. It arrived and I found they have different hardware. It's still 8266 and I was able to forl firmware, but there are problems in displaying and exchanging data.  
It seems that the thermostat is not communicating correctly with HA. See and set different temperatures. I used mqtt but doesn't work better, it seems not to dialogue correctly.
![1604062331365](https://user-images.githubusercontent.com/64415247/97708450-1b0c6080-1ab9-11eb-90c3-648f7453b2ab.jpg)
[log new Thermostat.txt](https://github.com/klausahrenberg/WThermostatBeca/files/5468789/log.new.Thermostat.txt)

**Comment by kocsishome** [comment] 2020-10-31 06:27
![97070579-a6798380-15d9-11eb-9c4d-89f909f5f650](https://user-images.githubusercontent.com/63285852/97772782-776b9080-1b4a-11eb-8f2c-d5c93850dd73.jpg)

**Comment by tbekavac** [comment] 2020-11-13 16:24
Hi! Same thing here :)
Duplicate of #144

**Comment by klausahrenberg** [comment] 2021-01-23 22:31
I implemented support for this new device DLX-LH01 in version 1.20i. Please test and report the unknown MCU commands. I will close this issue because it's a duplicate of #144 .

**Closed by klausahrenberg** 2021-01-23 22:31 UTC
