### ISSUE TITLE
Schedules / Clock | Pages not working 1.16 + 1.17

### ISSUE THREAD

**Issue by mf-1** [klausahrenberg/WThermostatBeca#137] opened 2020-09-29 18:26 UTC
Firmware 1.16 + 1.17 ... Schedules tab not working.

![image](https://user-images.githubusercontent.com/1529283/94599812-440abd00-0291-11eb-9d2e-d04df9d5a52e.png)

Firmware 1.17 ... Clock tab empty ...

![image](https://user-images.githubusercontent.com/1529283/94600256-f0e53a00-0291-11eb-86de-31d7f7c02684.png)

**Comment by GoNzCiD** [comment] 2020-09-29 21:39
I have the same issue

**Comment by klausahrenberg** [comment] 2020-09-30 07:13
Strange... Could be, that loading of old settings is the cause. Please try to unzip and flash the attachment. This firmware will reset the settings of thermostat (network settings not). Please try, if this fixes the faulty clock page.

[WThermostat_1.17_reset_settings.zip](https://github.com/klausahrenberg/WThermostatBeca/files/5303665/WThermostat_1.17_reset_settings.zip)

**Comment by mf-1** [comment] 2020-09-30 10:07
@klausahrenberg Have used another thermostat (1.11) to update ... Same issue. If I reload the page the output is different. Sometime more "data", sometimes not... Clock sometime is working, sometime blank.

I've just seen that the html tag is used twice. Also seen (partial) at my screen above.
Please find attached source code from schedules page...

[view-source_IP_schedules_.zip](https://github.com/klausahrenberg/WThermostatBeca/files/5304682/view-source_IP_schedules_.zip)

**Comment by klausahrenberg** [comment] 2020-10-03 07:08
Ok, I was able to reproduce the failure, if I change the thermostat model to BAC-002-ALC for example. Cause not known yet - give me time to check the issue

**Comment by mf-1** [comment] 2020-10-03 07:23
Sounds great. Maybe this helps. I'm using BHT-002GALW

**Comment by klausahrenberg** [comment] 2020-10-04 03:23
It's all about memory...
AsyncWebServer is faster and can handle multiple requests - but memory usage increases also. This caused corrupted html sites in some cases. It's fixed now in v1.18

**Closed by klausahrenberg** 2020-10-04 03:23 UTC
Labels: bug

**Comment by mf-1** [comment] 2020-10-04 08:48
acknowledged .... It's working with 1.18. Tested on another v1.11 I had.... thx!
