### ISSUE TITLE
BHT-002GCLW last state after Power los 220 V

### ISSUE THREAD

**Issue by flejur** [klausahrenberg/WThermostatBeca#173] opened 2020-12-30 07:07 UTC
Hello, I have a BHT-002GCLW with the firmware klausahrenberg 1.18. After a power interruption, the display of the thermostat turns on automatically (and heats even if he is in manual mode). Can he be set so that he is off or takes over the last state? Could not find any settings or entries here. Thanks for your help

**Comment by pashok2398** [comment] 2021-01-11 22:29
Duplicate of #148

**Comment by klausahrenberg** [comment] 2021-01-23 17:20
Problem confirmed, issue will be followed at #148 . At the moment no solution for this problem for device BHT-002.

**Closed by klausahrenberg** 2021-01-23 17:20 UTC
Labels: BHT-002 BHT-6000 BHT-3000
